[package]
name = "mailsv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
mailin = "0.6.0"
anyhow = "1.0.33"
async-io = "1.6.0"
futures-lite = "1.12.0"

mailparse = "0.13.8"
